In [33]:
import numpy as np
import locale
from datetime import datetime
locale.setlocale(locale.LC_ALL, 'pt_BR')

'pt_BR'

In [43]:
vendas_anos = np.array([[149, 499, 112, 430, 115, 390, 187, 316, 361, 483, 353, 400],
[258, 222, 461, 263, 384, 210, 452, 372, 417, 364, 468, 397],
[259, 329, 417, 132, 318, 256, 362, 496, 232, 132, 306, 174],
[117, 148, 480, 201, 160, 292, 146, 209, 298, 215, 358, 234],
[169, 229, 381, 119, 225, 270, 379, 272, 167, 332, 144, 359],
[358, 434, 228, 300, 122, 247, 142, 127, 191, 356, 450, 308],
[105, 251, 317, 147, 214, 280, 289, 338, 498, 133, 304, 225],
[156, 165, 299, 461, 290, 123, 451, 450, 353, 191, 167, 451],
[149, 377, 389, 176, 103, 439, 269, 132, 200, 391, 426, 175],
[137, 107, 229, 227, 198, 206, 432, 169, 323, 141, 155, 233]])

soma_anos = vendas_anos.sum(axis=1)
print(soma_anos.shape)
print(soma_anos)
print(soma_anos.max())
print(vendas_anos.max()) #Maior valor de venda de toda a matriz vendas_anos;
print(vendas_anos.max(axis=0)) #Maior valor de vendas a cada mês nos 10 anos;
print(vendas_anos.max(axis=1)) #Maior valor de vendas a cada ano;

anos = np.arange(2011, 2021) #Cria um array com os anos de 2011 até 2020
print(anos)
print(vendas_anos.argmax(axis=1))
meses = list(map(lambda x: datetime.strptime(str(x), "%m"), np.arange(1, 13)))
meses = list(map(lambda x: x.strftime("%B").title(), meses))

for i in range(len(anos)):
    indice_max_ano = vendas_anos[i, :].argmax() #calcula o índice do mês de maior venda no anos
    print(indice_max_ano)
    maior_venda_ano = vendas_anos[i, indice_max_ano] #retorna o maior valor de venda
    print(maior_venda_ano)
    print(f"A maior venda de {anos[i]} ocorreu no mês de {meses[indice_max_ano]} e foi de {maior_venda_ano} computadores")

(10,)
[3795 4268 3413 2858 3046 3263 3101 3557 3226 2557]
4268
499
[358 499 480 461 384 439 452 496 498 483 468 451]
[499 468 496 480 381 450 498 461 439 432]
[2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]
[ 1 10  7  2  2 10  8  3  5  6]
1
499
A maior venda de 2011 ocorreu no mês de Fevereiro e foi de 499 computadores
10
468
A maior venda de 2012 ocorreu no mês de Novembro e foi de 468 computadores
7
496
A maior venda de 2013 ocorreu no mês de Agosto e foi de 496 computadores
2
480
A maior venda de 2014 ocorreu no mês de Março e foi de 480 computadores
2
381
A maior venda de 2015 ocorreu no mês de Março e foi de 381 computadores
10
450
A maior venda de 2016 ocorreu no mês de Novembro e foi de 450 computadores
8
498
A maior venda de 2017 ocorreu no mês de Setembro e foi de 498 computadores
3
461
A maior venda de 2018 ocorreu no mês de Abril e foi de 461 computadores
5
439
A maior venda de 2019 ocorreu no mês de Junho e foi de 439 computadores
6
432
A maior venda de 2020 ocorreu no 