In [120]:
import numpy as np

In [121]:
visualizacao_stories = [
    [187, 120, 88, 70, 130, 168, 213],
    [0, 0, 42, 0, 0, 55, 77],
    [91, 0, 61, 0, 71, 121, 271],
    [0, 0, 0, 0, 187, 0, 0],
    [42, 23, 34, 0, 39, 29, 36]
]

pessoas = ['Raquel', 'Lucas', 'Daniel', 'Natalia', 'Anderson']
dias_semana = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado']

In [122]:
def informacoes_visualizacao_stories(contagem_visualizacao_stories):
    media_dia_semana = contagem_visualizacao_stories.mean(axis=0)
    print('A média de visualizações por dia de todas as pessoas juntas foi de:')
    for i in range(len(media_dia_semana)):
        print(f'{media_dia_semana[i]} -> {dias_semana[i]}')
    soma_stories_por_dia = contagem_visualizacao_stories.sum(axis=0)
    dia_maior_stories_somados = soma_stories_por_dia.argmax()
    print(f'\nO dia da semana com o maior número de visualizações de stories somadas foi {dias_semana[dia_maior_stories_somados]}.')
    soma_total_semana_pessoa = contagem_visualizacao_stories.sum(axis=1)
    pessoa_maior_num_semana = soma_total_semana_pessoa.argmax()
    print(f'\nA pessoa que teve o maior número de visualizações foi {pessoas[pessoa_maior_num_semana]}.')

In [123]:
visualizacao_stories = np.array(visualizacao_stories)
informacoes_visualizacao_stories(visualizacao_stories)

A média de visualizações por dia de todas as pessoas juntas foi de:
64.0 -> Domingo
28.6 -> Segunda
45.0 -> Terça
14.0 -> Quarta
85.4 -> Quinta
74.6 -> Sexta
119.4 -> Sábado

O dia da semana com o maior número de visualizações de stories somadas foi Sábado.

A pessoa que teve o maior número de visualizações foi Raquel.


In [124]:
visualizacao_stories_invalidos = np.array([
    [52, 68, 97, 55, -1, 98, -1],
    [53, -1, 38, -1, -1, 72, 49],
    [88, -1, 64, -1, 77, 130, 43],
    [-1, 30, -1, -1, -1, 182, -1],
    [41, 20, 33, -1, 37, 23, 7]
])

In [125]:
array_mascarado = np.ma.masked_where(visualizacao_stories_invalidos == -1, visualizacao_stories_invalidos )
novo_array_mascarado = array_mascarado.filled(0)
print(novo_array_mascarado)

[[ 52  68  97  55   0  98   0]
 [ 53   0  38   0   0  72  49]
 [ 88   0  64   0  77 130  43]
 [  0  30   0   0   0 182   0]
 [ 41  20  33   0  37  23   7]]


In [113]:
dados_ultimas_duas_semanas = np.add(novo_array_mascarado,visualizacao_stories)
informacoes_visualizacao_stories(dados_ultimas_duas_semanas)

A média de visualizações por dia de todas as pessoas juntas foi de:
110.8 -> Domingo
52.2 -> Segunda
91.4 -> Terça
25.0 -> Quarta
108.2 -> Quinta
175.6 -> Sexta
139.2 -> Sábado

O dia da semana com o maior número de visualizações de stories somadas foi Sexta.

A pessoa que teve o maior número de visualizações foi Raquel.
